language: php

php:
  - 5.5
  - 5.6

before_install:
  - 'composer selfupdate --no-interaction'

install:
  - 'composer install --no-interaction --dev --prefer-source'

script:
  - './vendor/bin/phpunit -c "./test/phpunit.xml" --testsuite "unit" --coverage-text'

notifications:
  email: false
